# Generated by Django 4.1.1 on 2022-09-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tag_line',
            new_name='tagline',
        ),
    ]
