# Generated by Django 3.2.15 on 2022-09-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20220926_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='description_ru',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='name_ru',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description_ru',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_ru',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='description_ru',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name_ru',
            new_name='name_uk',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='country_ru',
            new_name='country_uk',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='description_ru',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='tagline_ru',
            new_name='tagline_uk',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title_ru',
            new_name='title_uk',
        ),
        migrations.RenameField(
            model_name='movieshots',
            old_name='description_ru',
            new_name='description_uk',
        ),
        migrations.RenameField(
            model_name='movieshots',
            old_name='title_ru',
            new_name='title_uk',
        ),
    ]
